{% set name = "meshpy" %}
{% set uname = "MeshPy" %}
{% set version = "2026.1.1" %}
{% set sha256 = "21376b339a9d9c017c9bb1e9126f6595b344c8c7790e00ce6d46e929edd9d2ff" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  fn: {{ uname }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ uname[0] }}/{{ uname }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  script:
    # Need to parse MESON_ARGS to make sure meson finds the correct executables for cross-compilation.
    - $PYTHON -m build -w -n -x -Csetup-args=${MESON_ARGS// / -Csetup-args=}    # [unix]
    - $PYTHON -m pip install dist/meshpy*.whl                                   # [unix]
    - python -m pip install . -vv                                               # [win]
    - echo src/cpp/tetgen-LICENSE >> doc/faq.rst
  skip: true  # [py<310]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - python-build
    - pip
    - numpy
    - pybind11
    - meson-python
  run:
    - python
    - numpy

test:
  source_files:
    - test/*
  requires:
    - pytest
    - pip
  commands:
    - pip check
    - pytest test
  imports:
    - meshpy

about:
  home: https://github.com/inducer/meshpy
  license: MIT AND LicenseRef-Proprietary-Triangle AND AGPL-3.0-or-later
  license_file: doc/faq.rst
  summary: Triangular and Tetrahedral Mesh Generator
  description: |
    MeshPy offers quality triangular and tetrahedral mesh generation for
    Python. Meshes of this type are mainly used in finite-element
    simulation codes, but also have many other applications ranging from
    computer graphics to robotics.
  doc_url: https://documen.tician.de/meshpy
  dev_url: https://github.com/inducer/meshpy

extra:
  recipe-maintainers:
    - inducer
    - isuruf
    - mwtoews
